// mobile/src/pages/EventPage.tsx
import { IonIcon, IonRouterOutlet, IonTabBar, IonTabButton, IonTabs } from "@ionic/react";
import { IonReactRouter } from "@ionic/react-router";
import { Redirect, Route, useParams } from "react-router";
import EventSchedule from "./EventSchedule";
import { playCircle, star } from "ionicons/icons";
import { useState } from "react";
import useEventDetails from "../hooks/useEventDetails";

const EventPage: React.FC = () => {
    const params = useParams<{ eventId: string }>();
    const eventId = params.eventId
    const eventDetails = useEventDetails({eventId: params.eventId}) ?? undefined
    const [day, setDay] = useState<string | undefined>(undefined)

    if (!day && (eventDetails?.info.days.length ?? 0) > 0) {
        setDay(eventDetails?.info.days[0])
    }

    return <IonReactRouter>
            <IonTabs>
                <IonRouterOutlet id="event-router">
                    <Redirect exact path="/events/:eventId" to="/events/:eventId/schedule" />
                    <Route path="/events/:eventId/schedule"  exact={true}
                            render={() => 
                                <EventSchedule 
                                    eventDetails={eventDetails} favoritesOnly={false} 
                                    day={day} onDayChange={setDay} />} />
                    <Route path="/events/:eventId/favorites"  exact={true}
                            render={() => 
                                <EventSchedule 
                                    eventDetails={eventDetails} favoritesOnly={true} 
                                    day={day} onDayChange={setDay} />} />
                </IonRouterOutlet>
                <IonTabBar slot="bottom">
                    <IonTabButton tab="event" href={`/events/${eventId}/schedule`}>
                        <IonIcon icon={playCircle} />
                    </IonTabButton>
                    <IonTabButton tab="event-favorites" href={`/events/${eventId}/favorites`}>
                        <IonIcon icon={star} />
                    </IonTabButton>
                </IonTabBar>
            </IonTabs>
            </IonReactRouter>
}
export default EventPage

// mobile/src/views/EventPage.vue
<template>
  <ion-page>
    <ion-tabs>
      <current-event-header />
      <ion-router-outlet></ion-router-outlet>
      <ion-tab-bar slot="bottom">
        <ion-tab-button tab="schedule" @click="router.push({name: 'eventSchedule', params: {eventId}})">
          <ion-icon aria-hidden="true" :icon="calendar" />
          <ion-label>Schedule</ion-label>
        </ion-tab-button>

        <ion-tab-button tab="favorites" @click="router.push({name: 'eventFavorites', params: {eventId}})">
          <ion-icon aria-hidden="true" :icon="star" />
          <ion-label>Favorites</ion-label>
        </ion-tab-button>

        <ion-tab-button tab="feedbacks" @click="router.push({name: 'eventFeedbacks', params: {eventId}})">
          <ion-icon aria-hidden="true" :icon="chatbox" />
          <ion-label>Feedbacks</ion-label>
        </ion-tab-button>

        <ion-tab-button tab="infos" @click="router.push({name: 'eventInformations', params: {eventId}})">
          <ion-icon aria-hidden="true" :icon="information" />
          <ion-label>Infos</ion-label>
        </ion-tab-button>
      </ion-tab-bar>
    </ion-tabs>
  </ion-page>
</template>

<script setup lang="ts">
import {
    IonTabBar,
    IonTabButton,
    IonTabs,
    IonLabel,
    IonIcon,
    IonPage,
    IonRouterOutlet,
} from '@ionic/vue';
import {calendar, chatbox, information, star} from 'ionicons/icons';
import {ref} from "vue";
import {useRoute, useRouter} from "vue-router";
import CurrentEventHeader from "@/components/CurrentEventHeader.vue";

const router = useRouter();
const route = useRoute();
const eventId = ref(route.params.eventId);

</script>
